# Generated by Django 5.0.2 on 2024-02-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_smartphones_memory_alter_smartphones_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones',
            name='release_date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
