# Generated by Django 5.0.2 on 2024-03-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_smartphones_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
